#!/bin/sh

TMPHOSTS="$(mktemp)"
TMPHOSTS2="$(mktemp)"

curl -sSL "https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews/hosts" | grep '^0\.0\.0\.0' > "${TMPHOSTS}"
{
  curl -sSL "https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&mimetype=plaintext&useip=0.0.0.0" | grep '^0\.0\.0\.0'
  curl -sSL "https://blocklistproject.github.io/Lists/abuse.txt" | grep '^0\.0\.0\.0'
  curl -sSL "https://blocklistproject.github.io/Lists/ads.txt" | grep '^0\.0\.0\.0'
  curl -sSL "https://blocklistproject.github.io/Lists/malware.txt" | grep '^0\.0\.0\.0'
} >> "${TMPHOSTS}"

cat > "${TMPHOSTS2}"<< EOF
127.0.0.1 local
127.0.0.1 localhost
127.0.0.1 localhost.localdomain
127.0.1.1 $(hostname --short) $(hostname --fqdn)
::1 localhost
::1 ip6-localhost ip6-loopback
fe80::1%lo0 localhost
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
ff02::3 ip6-allhosts
EOF

grep -E -v '^#|^$|^\s.*#' "${TMPHOSTS}" | strings | sort | uniq >> "${TMPHOSTS2}"
cp "${TMPHOSTS2}" "/etc/hosts"
echo "${TMPHOSTS2}"
