---
- name: Verify
  hosts: all
  any_errors_fatal: true

  tasks:
    - name: Reboot host
      become: true
      ansible.builtin.reboot:

    - name: Wait for the host and reconnect
      ansible.builtin.wait_for:
        port: 22
        host: '{{ (ansible_ssh_host | default(ansible_host)) | default(inventory_hostname) }}'
        delay: 10
        timeout: 120

    - name: Include default vars
      ansible.builtin.include_vars:
        dir: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/defaults/"
        extensions:
          - 'yml'

    - name: Include host vars
      ansible.builtin.include_vars:
        file: "{{ lookup('env', 'MOLECULE_EPHEMERAL_DIRECTORY') }}/inventory/host_vars/{{ ansible_hostname }}"

    - name: Verify host in /etc/hosts
      ansible.builtin.shell: |
        set -o pipefail
        grep "{{ item }}" /etc/hosts
      args:
        executable: /bin/bash
      register: local_host
      with_items:
        - '^127.0.0.1\slocalhost.localdomain$'
        - '^127.0.1.1\s{{ ansible_hostname }}'
      changed_when: false
      failed_when: local_host.rc != 0

    - name: Verify host count in /etc/hosts
      ansible.builtin.shell: |
        set -o pipefail
        grep '^0.0.0.0\s' /etc/hosts | wc -l
      args:
        executable: /bin/bash
      register: hosts_count
      changed_when: false
      failed_when: hosts_count.stdout | int <= 10000

    - name: Verify DNS server using dig @127.0.0.1
      ansible.builtin.shell:
        dig @127.0.0.1 proton.me
      args:
        executable: /bin/bash
      register: dig_server
      failed_when: 'not "SERVER: 127.0.0.1" in dig_server.stdout'
      changed_when: 'not "SERVER: 127.0.0.1" in dig_server.stdout'

    - name: Verify DNS server using dig
      ansible.builtin.shell:
        dig proton.me
      args:
        executable: /bin/bash
      register: dig_server
      failed_when: 'not "SERVER: 127.0.0.1" in dig_server.stdout'
      changed_when: 'not "SERVER: 127.0.0.1" in dig_server.stdout'

    - name: Verify DNS cache using dig
      ansible.builtin.command: dig proton.me
      register: dig_cache
      failed_when: 'not "Query time: 0 msec" in dig_cache.stdout'
      changed_when: 'not "Query time: 0 msec" in dig_cache.stdout'

    - name: Stat /etc/cron.daily/generate_hosts
      ansible.builtin.stat:
        path: /etc/cron.daily/generate_hosts
      register: daily_generate_hosts

    - name: Assert /etc/cron.daily/generate_hosts
      ansible.builtin.assert:
        that:
          - daily_generate_hosts.stat.mode == "0755"
        success_msg: "{{ daily_generate_hosts.stat.path }} has correct permissions: {{ daily_generate_hosts.stat.mode }}"
        fail_msg: "{{ daily_generate_hosts.stat.path }} permissions are incorrect: {{ daily_generate_hosts.stat.mode }}"
