---
on:
  schedule:
    - cron: "0 5 * * */3"
name: Ansible Lint Main - Scheduled

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - name: Lint Ansible Playbook
        uses: ./action-lint
